name: Test Self-Hosted Runner
on: [push]

jobs:
  test:
    runs-on: self-hosted  
    steps:
      - name: Check Runner
        run: |
          echo "Success! Running on: $(uname -a)"
          echo "Runner location: $(pwd)"
